- bin/install.sh
I have encountered some issues with the install.sh script on Gentoo linux. Installing Java thrown errors (apt-get...) and JAVA_HOME detection failed (because in Gentoo javac is a symlink to "/usr/libexec/eselect-java/run-java-tool.bash").
The script now:
* lets you decide if you want to install Java or not, and asks you for your distro if you do (currently only Debian/Ubuntu is supported),
* checks if JAVA_HOME is correct and in case of failure lets the user input the path manually,
* uses "read -e -p ..." which enables auto-completion of paths.
I have tested it only on Gentoo.
> Improve Java installation and locating in install.sh

- examples/scala-parallel-similarproduct/filterbyyear/README.md
filterbyyear README.MD Changes and mail config
> filterbyyear README.MD Changes

- docs/manual/source/demo/tapster.html.md
Currently, if someone is following this tutorial they will not see any comic as database is empty. They will see a loading spinner and error in their developer tool console. This gives a feeling that something is broken.
> Import data into database before starting rails application

- tools/src/main/scala/admin/CommandClient.scala
- tools/src/main/scala/admin/README.md
Closes: #PDIO-557
Added initial code for train command
Updated doc in README.md
> Fixed bug when create new app that does not return the key of the app

- examples/scala-parallel-similarproduct/add-and-return-item-properties/README.md
- examples/scala-parallel-similarproduct/add-and-return-item-properties/build.sbt
- examples/scala-parallel-similarproduct/add-and-return-item-properties/project/pio-build.sbt
- examples/scala-parallel-similarproduct/add-and-return-item-properties/src/main/scala/ALSAlgorithm.scala
- examples/scala-parallel-similarproduct/add-and-return-item-properties/src/main/scala/LikeAlgorithm.scala
- upgrade add-and-return-item-properties example to version 0.9
- fix links in README.md
> upgrade add-and-return-item-properties example to version 0.9, fix doc links

- docs/manual/source/community/contribute-sdk.html.md
- Specify status codes when errors occur
- Add examples of JSON objects in the Engine Client's request and response
> Update the contributors' guide for writing a SDK

- examples/scala-parallel-recommendation/filter-by-category/README.md
- examples/scala-parallel-recommendation/filter-by-category/build.sbt
- examples/scala-parallel-recommendation/filter-by-category/data/import_eventserver.py
- examples/scala-parallel-recommendation/filter-by-category/data/send_query.py
- examples/scala-parallel-recommendation/filter-by-category/engine.json
- examples/scala-parallel-recommendation/filter-by-category/project/assembly.sbt
- examples/scala-parallel-recommendation/filter-by-category/project/pio-build.sbt
- examples/scala-parallel-recommendation/filter-by-category/src/main/scala/ALSAlgorithm.scala
- examples/scala-parallel-recommendation/filter-by-category/src/main/scala/ALSModel.scala
- examples/scala-parallel-recommendation/filter-by-category/src/main/scala/DataSource.scala
- examples/scala-parallel-recommendation/filter-by-category/src/main/scala/Engine.scala
- examples/scala-parallel-recommendation/filter-by-category/src/main/scala/Preparator.scala
- examples/scala-parallel-recommendation/filter-by-category/src/main/scala/Serving.scala
Recommend items, limiting results to those belonging to a category specified by the query.
A detailed explanation of changes can be found in the file README.md
> Example of recommendation template with filtering by category

- bin/compute-classpath.sh
- bin/install.sh
- bin/load-pio-env.sh
- bin/pio
- bin/pio-class
- bin/pio-daemon
- bin/pio-shell
- bin/pio-start-all
- bin/pio-stop-all
- make-distribution.sh
This will:
* add enhancements for bash scripts in bin
* add colors to important messages in bash scripts
> Adds enhancements for bash files in bin and make-distributions.sh

- docs/manual/source/templates/complementarypurchase/dase.html.md.erb
This is part of documentation describing minBasketSize algorithm property
> Minimum basket size parameter description

- data/src/main/scala/io/prediction/data/webhooks/mailchimp/MailChimpConnector.scala
- data/src/test/scala/io/prediction/data/webhooks/mailchimp/MailChimpConnectorSpec.scala
- data/test-form.sh
Added connector code and tests for MailChimp webhooks, for all the events listed in the MailChimp API (https://apidocs.mailchimp.com/webhooks/).
> MailChimp Webhook Connector 

- docs/manual/source/demo/community.html.md
Demonstrates how to integrate a PredictionIO engine with an iOS app via the PredictionIO Swift SDK
> Add Tapster iOS demo

- .gitattributes
- .gitignore
- .travis.yml
- bin/travis/pio-start-travis
- bin/travis/pio-stop-travis
- conf/pio-env.sh.travis
- core/src/main/scala/io/prediction/controller/CustomQuerySerializer.scala
- core/src/main/scala/io/prediction/workflow/FakeWorkflow.scala
- core/src/main/scala/io/prediction/workflow/JsonExtractor.scala
- data/src/main/scala/io/prediction/data/api/EventInfo.scala
- data/src/main/scala/io/prediction/data/api/EventServer.scala
- data/src/main/scala/io/prediction/data/api/PluginsActor.scala
- data/src/main/scala/io/prediction/data/storage/DataMap.scala
- data/src/main/scala/io/prediction/data/storage/DateTimeJson4sSupport.scala
- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCApps.scala
- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCChannels.scala
- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCEngineManifests.scala
- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCLEvents.scala
- data/src/main/scala/io/prediction/data/storage/jdbc/StorageClient.scala
- data/src/main/scala/io/prediction/data/store/Common.scala
- e2/src/main/scala/io/prediction/e2/engine/CategoricalNaiveBayes.scala
- scalastyle-config.xml
- tools/src/main/scala/io/prediction/tools/admin/AdminAPI.scala
- tools/src/main/scala/io/prediction/tools/admin/CommandClient.scala
- tools/src/main/scala/io/prediction/tools/console/App.scala
- tools/src/main/scala/io/prediction/tools/console/Template.scala
- tools/src/main/scala/io/prediction/tools/dashboard/CorsSupport.scala
* enable travis for `develop` branch
* use JVM from travis instead of Ruby VM
* prepare spark, postgre and hbase for pio
* build doc
* run unit test using built-in sbt (current is 0.13.7)
> Enabling unit test in travis CI

- .travis.yml
- project/plugins.sbt
* `sbt/sbt clean coverage test` to instrument then collect coverage data from all unit tests
* current coverage is 1.62% in total, need more unit tests
* switch travis to use container-based infra for better RAM allocation (potentially solve the problem with time out jobs)
> Enabling code coverage using scoverage

- docs/manual/source/customize/index.html.md
> Fix tiny typo

- docs/manual/source/templates/recommendation/customize-data-prep.html.md
Fix for docs for 0.9.2 engine.json.
> Updating to use 0.9.2 "appName" instead of "appId"

- core/src/main/scala/io/prediction/workflow/Workflow.scala
- data/src/main/scala/io/prediction/data/storage/Storage.scala
- tools/build.sbt
…llowed in Scala 2.11) & specify semverfi dep as 2.10 (for compatibility w/ Scala 2.11
> Make compile w/ Scala 2.11 work

- data/src/main/scala/io/prediction/data/api/EventServer.scala
- data/src/main/scala/io/prediction/data/storage/EventJson4sSupport.scala
- data/test.sh
- data/very_long_batch_request.txt
An attempt to implement support for batch requests that was discussed on the [development google group] (https://groups.google.com/forum/#!topic/predictionio-dev/Fd_Dt2Lhvy4).
The specification can be found [here](https://docs.google.com/document/d/1byXQ7eM1pJ1g8O4hVBvEi1AuMSCx7osSrJk3FKwAaz4/edit). 
@dszeto You mentioned that I should create tasks on JIRA but I'm not sure what to create so please advise if I still need to.
> Batch requests support

- docs/manual/source/templates/vanilla/dase.html.md.erb
> Updated code in Vanilla dase.html.md.erb

- docs/manual/source/templates/recommendation/quickstart.html.md.erb
> bugfix. fix a json mistake.

- sbt/sbt-launch-lib.bash
Fix fo following issue:
https://github.com/PredictionIO/PredictionIO/issues/146
> Change repo order, and follow redirect with curl

- core/src/main/scala/io/prediction/controller/package.scala
> Fixed tiny typo

- docs/manual/source/demo/tapster.html.md
Correct localhost link to point to localhost instead of localhost.com
> Correct localhost link to point to localhost

- docs/manual/source/demo/tapster.html.md
Since the list was mashed together into this statement, it was extremely unclear what this sentence was trying to do.
> Add bullets to list items

- docs/manual/source/evaluation/paramtuning.html.md
I found the paragraph on 148 very hard to parse. I hope this is an improvement.
> Edit for clarity and grammar

- build.sbt
- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCPEvents.scala
Using dataframe API of apache spark instead of scalikejdbc library when writing to RDBMS. 
Closes #179
> Fix "pio import" error using jdbc in cluster mode.

- tools/src/main/scala/io/prediction/tools/imprt/FileToEvents.scala
> Add better error reporting to pio import

- tools/src/main/scala/io/prediction/tools/console/App.scala
- tools/src/main/scala/io/prediction/tools/console/Console.scala
- tools/src/main/twirl/io/prediction/tools/console/app.scala.txt
Add --yes, -y option when deleting app and channel.
It is useful to execute a batch script
Closes #149
> Delete application data in non-interactive mode

- docs/manual/source/deploy/index.html.md
- docs/manual/source/evaluation/evaluationdashboard.html.md
> Doc dashboard server and engine server security concerns

- core/src/main/scala/io/prediction/controller/Deployment.scala
- core/src/main/scala/io/prediction/controller/Engine.scala
- core/src/main/scala/io/prediction/controller/Evaluation.scala
- core/src/main/scala/io/prediction/controller/FastEvalEngine.scala
- core/src/main/scala/io/prediction/controller/LServing.scala
- core/src/main/scala/io/prediction/controller/Metric.scala
- core/src/main/scala/io/prediction/controller/MetricEvaluator.scala
- core/src/main/scala/io/prediction/controller/package.scala
- core/src/main/scala/io/prediction/core/BaseEngine.scala
- core/src/main/scala/io/prediction/core/BaseEvaluator.scala
- core/src/main/scala/io/prediction/workflow/CoreWorkflow.scala
- core/src/main/scala/io/prediction/workflow/FakeWorkflow.scala
- data/src/main/scala/io/prediction/data/storage/BiMap.scala
- data/src/main/scala/io/prediction/data/storage/elasticsearch/ESChannels.scala
- data/src/main/scala/io/prediction/data/storage/hbase/PIOHBaseUtil.scala
- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCLEvents.scala
- data/src/main/scala/io/prediction/data/store/LEventStore.scala
- data/src/main/scala/io/prediction/data/webhooks/mailchimp/MailChimpConnector.scala
- e2/src/main/scala/io/prediction/e2/engine/BinaryVectorizer.scala
- scalastyle-config.xml
- tools/src/main/scala/io/prediction/tools/RunWorkflow.scala
- tools/src/main/scala/io/prediction/tools/admin/CommandClient.scala
- tools/src/main/scala/io/prediction/tools/dashboard/CorsSupport.scala
This PR adds an Scala Style checker rule `WhitespaceEndOfLineChecker`.
> Add a rule WhitespaceEndOfLineChecker in Scala Style Checker

- docs/manual/source/templates/similarproduct/dase.html.md.erb
- docs/manual/source/templates/similarproduct/quickstart.html.md.erb
changes for closed [PR#8](https://github.com/PredictionIO/template-scala-parallel-similarproduct/pull/8)
@k4hoo
> doc changes for pull8 in template-scala-parallel-similarproduct

- README.md
Fixed the link to the right url
> [PIO-4] Fix travis CI url in README.md

- core/src/main/scala/io/prediction/workflow/CoreWorkflow.scala
- core/src/main/scala/io/prediction/workflow/CreateServer.scala
- core/src/main/scala/io/prediction/workflow/WorkflowUtils.scala
- tools/src/main/scala/io/prediction/tools/console/Console.scala
Apart from not being implemented, upgrade check was causing SSL Handshake exceptions during the engine building.
See also: #243
> [PIO-8] Remove upgrade check

- bin/install.sh
Updates installer to install Java 8, which is required by PredictionIO
> Added OpenJDK8 to install.sh script #223

- data/test-normal.sh
- data/test3.sh
- docs/manual/obsolete/tutorials/enginebuilders/stepbystep/index.html.md
- docs/manual/source/datacollection/eventapi.html.md
- docs/manual/source/partials/shared/install/_postgres.html.erb
- docs/manual/source/templates/classification/add-algorithm.html.md
- docs/manual/source/templates/classification/dase.html.md.erb
- docs/manual/source/templates/classification/quickstart.html.md.erb
- docs/manual/source/templates/complementarypurchase/quickstart.html.md.erb
- docs/manual/source/templates/ecommercerecommendation/dase.html.md.erb
- docs/manual/source/templates/ecommercerecommendation/quickstart.html.md.erb
- docs/manual/source/templates/javaecommercerecommendation/quickstart.html.md.erb
- docs/manual/source/templates/leadscoring/quickstart.html.md.erb
- docs/manual/source/templates/productranking/dase.html.md.erb
- docs/manual/source/templates/productranking/quickstart.html.md.erb
- docs/manual/source/templates/recommendation/dase.html.md.erb
- docs/manual/source/templates/similarproduct/dase.html.md.erb
- docs/manual/source/templates/similarproduct/multi-events-multi-algos.html.md.erb
- docs/manual/source/templates/similarproduct/quickstart.html.md.erb
This PR fixes miscellaneous typos and and corrects documentation across the documentation.
The purpose of this PR is to tie up the small PRs related with typos and documentation and fix the related changes across documentation rather than only in some places.
These were initially proposed by @shanethehat, @linkthrow, @jamesward and @IAlwaysBeCoding and based on these PRs below.
Closes apache/incubator-predictionio#220
Closes apache/incubator-predictionio#228
Closes apache/incubator-predictionio#234
Closes apache/incubator-predictionio#240
> [MINOR] Miscellaneous typos and corrections in documentation

- data/src/main/scala/org/apache/predictionio/data/storage/jdbc/JDBCPEvents.scala
- docs/manual/source/gallery/templates.yaml
Request to merge templates build with new release version of predictionio 0.10.0-incubating.
> [PIO-34]Update templates.yaml

- docker/README.md
- docker/bin/pio-docker
- docker/deploy/run.sh
- docker/docker-compose.deploy.yml
- docker/docker-compose.spark.yml
- docker/docker-compose.yml
- docker/elasticsearch/docker-compose.base.yml
- docker/elasticsearch/docker-compose.event.yml
- docker/elasticsearch/docker-compose.meta.yml
- docker/localfs/docker-compose.model.yml
- docker/mysql/docker-compose.base.yml
- docker/mysql/docker-compose.event.yml
- docker/mysql/docker-compose.meta.yml
- docker/mysql/docker-compose.model.yml
- docker/pgsql/docker-compose.base.yml
- docker/pgsql/docker-compose.event.yml
- docker/pgsql/docker-compose.meta.yml
- docker/pgsql/docker-compose.model.yml
- docker/pio/Dockerfile
- docker/pio/pio_run
- docker/templates/.keep
Please see [README](https://github.com/marevol/predictionio/blob/docker/docker/README.md).
> [PIO-86] Docker support

- docs/manual/source/templates/recommendation/quickstart.html.md.erb
> [PIO-195] Improve readability and grammar
