apache/predictionio

- core/src/main/scala/controller/DataSource.scala
- core/src/main/scala/controller/Engine.scala
- core/src/main/scala/controller/Evaluator.scala
- core/src/main/scala/controller/Workflow.scala
- core/src/main/scala/controller/java/JavaDataSource.scala
- core/src/main/scala/core/BasePreparator.scala
- core/src/main/scala/workflow/Workflow.scala
- core/src/main/scala/workflow/WorkflowUtils.scala
- data/src/main/scala/storage/AccessKeys.scala
- data/src/main/scala/storage/DataMap.scala
- data/src/main/scala/storage/Event.scala
- data/src/main/scala/storage/EventJson4sSupport.scala
- data/src/main/scala/storage/LEvents.scala
- data/src/main/scala/storage/PEventAggregator.scala
- data/src/main/scala/storage/hbase/HBEventsUtil.scala
- data/src/main/scala/storage/hbase/PIOHBaseUtil.scala
- data/src/main/scala/storage/hbase/upgrade/HB_0_8_0.scala
- data/src/main/scala/view/LBatchView.scala
- data/src/main/scala/view/PBatchView.scala
- engines/src/main/scala/base/EventsDataSource.scala
- engines/src/main/scala/base/PEventsDataSource.scala
- engines/src/main/scala/base/Preparator.scala
- engines/src/main/scala/base/mahout/AbstractNCItemBasedAlgorithm.scala
- engines/src/main/scala/itemrank/EventsDataSource.scala
- engines/src/main/scala/itemrank/ItemRankDetailedEvaluator.scala
- engines/src/main/scala/util/Util.scala
Fix typos and commonly misspelled words in method / inline documentation
> Fix typos in documentation

- tools/src/main/scala/RegisterEngine.scala
- tools/src/main/scala/RunServer.scala
- tools/src/main/scala/RunWorkflow.scala
- tools/src/main/scala/Runner.scala
- tools/src/main/scala/console/AccessKey.scala
- tools/src/main/scala/console/App.scala
- tools/src/main/scala/console/Console.scala
- tools/src/main/scala/console/Export.scala
- tools/src/main/scala/console/Import.scala
- tools/src/main/scala/console/Template.scala
- tools/src/main/scala/dashboard/Dashboard.scala
- tools/src/main/scala/export/EventsToFile.scala
- tools/src/main/scala/imprt/FileToEvents.scala
Most style violations were:
+ multiline if block without braces
+ public methods having explicit type
+ license header
> Fix tools to be consistent with scalastyle

- bin/install.sh
I encountered an error before where interrupting the tar download would cause subsequent install attempts to fail. Deleting the tmp file would make sure it gets download again.
> Delete tmp files in case corrupted

- bin/pio-shell
Add a script to start the PIO shell. There are two modes to start the shell.
1) `pio-shell`:
Start the pio shell by sbt. It includes the pio library.
2) `pio-shell --with-spark`
Start the pio shell by spark-shell. It includes both pio library
and the Apache Spark. It requries the Apache Spark setup and also takes
longer to start.
For example, https://gist.github.com/whhone/016088d3c3dfd73aaf9f
> [pio-shell] interactive PIO shell

- docs/manual/source/install/install-sourcecode.html.md.erb
BTW why are their both hbase conf and root variable in pio-env.sh? Seems like conf can be derived from the root. Conf should be kept with the HBase installation directory don't you think? That way the binary and config can be changed independent of PIO. HBase can then be treated as independent of PIO by experts and still works when bundled.
Following the HBase install quickstart leads one to believe the conf is with HBase, not in pio/conf. So there is confusion where you tell the user to edit the hbase/conf but the edits are ignored by pio-start-all since it finds the hbase conf at pio/conf.
The instructions will create a working installation but this seems a bit inconsistent.
> Install from source build and config instruction tweaks

- NOTICE.txt
- core/build.sbt
- core/src/main/scala/io/prediction/controller/Utils.scala
- core/src/main/scala/io/prediction/workflow/CoreWorkflow.scala
- core/src/main/scala/io/prediction/workflow/CreateServer.scala
Adds support for serializing via kyro Java synchronized Collections and Maps created with Collections.synchronized*.  To achieve this I used de.javakaffee.kryo-serializers. This project also contains serializers for many other types and they can be easily added in the future if needed.
> Add support for serializing synchronized collections

- docs/manual/source/datacollection/batchimport.html.md
In the python sdk part, the script writes to my_events.json. In the example line below events.json is used.
When learning PredictionIO by copy-pasting examples without really getting what one is doing this might be confusing (That is the way I learned it in the first place :-)).
So would like to I suggest to be consistent in the SDK and line examples in this case.
> Changed events.json into my_events.json

- bin/pio-start-all
I'm using Fedora with Oracle Java that installed manually. 
During **pio-start-all**, I will see below error message:
> PredictionIO/bin/pio-start-all: line 28: jps: command not found
For my case, the **jps** is available in *JAVA_HOME/bin/jps* but not in *PATH*, unless configure **alias** or **update-alternatives** for **jps** manually. 
Suggest to call **jps** from *JAVA_HOME/bin* if *JAVA_HOME* is set, else remain to current behavior.
> Call jps from JAVA_HOME if JAVA_HOME is set

- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCLEvents.scala
When testing the Event Server with `data/test.sh` using PostgreSQL as datasource, the last test failed with the following message error.
```
400 Bad Request
Server: spray-can/1.3.2
Date: Tue, 21 Jul 2015 12:05:33 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 108
{"message":"org.postgresql.util.PSQLException: ERROR: column \"starttime\" does not exist\n  Position: 303"}
expect 200
```
> Fix a bug due to an invalid column name when using JDBC as data source

- data/src/main/scala/io/prediction/data/storage/Storage.scala
- manifest.json
added the ability to grab the auto-generated config data for a storage client so we can create an Elasticsearch transport client that understands clusternames and hosts as defined in pio-env
> opened ability to get elasticsearch client config

- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCApps.scala
JDBCApps. Fixed typo in INSERT SQL statement.
It was failing when MYSQL was used as a backend
> JDBCApps. Fixed typo in INSERT SQL statement

- bin/install.sh
The `source_setup` variable is not defined in Docker mode, so no database is installed.
> Fix install.sh for Docker mode (Elastic Search + Hbase not installed)

- docs/manual/source/demo/tapster.html.md
It seems that asterisks for bullets work for github readme markdown, but not when rendered on the site. Further down this page, around lines 290-293, dashes are used instead. I assume these will now render properly.
> Use - instead of * for bullets

- docs/manual/source/datacollection/analytics-zeppelin.html.md.erb
The existing installation can possibly output errors with incompatible version 0.0.20 of frontend-maven-plugin. Since it is also deprecated, it is better to change the link to the new one: https://github.com/apache/incubator-zeppelin.git
> Update deprecated zeppelin link to incubator link

- data/src/main/scala/io/prediction/data/storage/jdbc/JDBCLEvents.scala
- docs/manual/source/system/anotherdatastore.html.md
Improvement performance when findByEntity is called.
Closes #159
> Change data type of event table to varchar(255)  when creating index.

- data/src/main/scala/io/prediction/data/storage/jdbc/StorageClient.scala
- docs/manual/source/system/anotherdatastore.html.md
Add CONNECTIONS property for jdbc setting in pio-env.sh. 
It allows user to be able to set max size of connection pool instead of default value.
Closes #176
> fix Cannot get a connection, pool error Timeout waiting for idle object

- bin/install.sh
When installing pio using the install.sh script, users that subscribe to
updates submit their email to a direct.prediction.io endpoint using
http. Email is PII and should be transmitted using https.
> Use https when submitting user email to pio

- data/src/main/scala/org/apache/predictionio/data/api/EventServer.scala
- data/src/main/scala/org/apache/predictionio/data/webhooks/segmentio/SegmentIOConnector.scala
- scalastyle-config.xml
As described in [PIO-12](https://issues.apache.org/jira/browse/PIO-12), it seems there are some basic rules missing. This PR adds the rules below:
- `FileTabChecker`
This complies http://docs.scala-lang.org/style/indentation
- `NonASCIICharacterChecker`
Currently, there are some weird non-ascii characters such as, `⇒` instead of `=>` and `→` instead of `->`. 
- `SpaceAfterCommentStartChecker`
Please refer [this](http://www.scalastyle.org/rules-dev.html#org_scalastyle_scalariform_SpaceAfterCommentStartChecker). Both comply [Java doc style](http://www.oracle.com/technetwork/articles/java/index-137868.html) and [Scala doc style](http://docs.scala-lang.org/style/scaladoc.html).
> [PIO-12] Add Scala style rules, FileTabChecker, NonASCIICharacterChecker and SpaceAfterCommentStartChecker

- data/src/main/scala/org/apache/predictionio/data/view/DataView.scala
- docs/manual/source/install/index.html.md.erb
- tools/src/main/scala/org/apache/predictionio/tools/export/EventsToFile.scala
This PR simply replaces the deprecated usage of Spark API in 1.4.0.
So, this PR replaces,
- `parquetFile` to `read.parquet` (See [here](https://github.com/apache/spark/blob/branch-1.4/sql/core/src/main/scala/org/apache/spark/sql/SQLContext.scala#L1099))
```
- sqlContext.parquetFile(fileName)
+ sqlContext.read.parquet(fileName)
```
- `saveAsParquetFile` to  `write.mode(SaveMode.ErrorIfExists).parquet` (See [here]( https://github.com/apache/spark/blob/branch-1.4/sql/core/src/main/scala/org/apache/spark/sql/DataFrame.scala#L1503-L1508))
```
- df.saveAsParquetFile(fileName)
+ df.write.mode(SaveMode.ErrorIfExists).parquet(fileName)
```
- `jsonRDD` to `read.json` (See [here](https://github.com/apache/spark/blob/branch-1.4/sql/core/src/main/scala/org/apache/spark/sql/SQLContext.scala#L1145-L1148) …
> [MINOR] Replace the deprecated usage of Spark API

- CONTRIBUTING.md
- README.md
- RELEASE.md
- build.sbt
- conf/pio-env.sh.template
- core/src/main/scala/org/apache/predictionio/controller/package.scala
- core/src/main/scala/org/apache/predictionio/workflow/WorkflowUtils.scala
- data/README.md
- examples/experimental/scala-parallel-recommendation-cat/README.md
- examples/scala-parallel-classification/custom-attributes/README.md
- examples/scala-parallel-ecommercerecommendation/train-with-rate-event/README.md
- examples/scala-parallel-ecommercerecommendation/weighted-items/README.md
- examples/scala-parallel-recommendation/filter-by-category/README.md
- examples/scala-parallel-similarproduct/add-and-return-item-properties/README.md
- examples/scala-parallel-similarproduct/add-rateevent/README.md
- examples/scala-parallel-similarproduct/filterbyyear/README.md
- examples/scala-parallel-similarproduct/multi/README.md
- examples/scala-parallel-similarproduct/no-set-user/README.md
- examples/scala-parallel-similarproduct/recommended-user/README.md
Update URLs in current develop codebase.
- CONTRIBUTING.md Updates the file since it has been out-of-date. No agreement should be signed anymore.
- README.md Creates a new JIRA [PIO-13](https://issues.apache.org/jira/browse/PIO-13) for updating the document dependency check.
- RELEASE.md Some of the links here are missing and have no replacement.
- URLs in docs are ignored in this PR. I believe URLs in docs will be fixed in [PIO-6](https://issues.apache.org/jira/browse/PIO-6).
- tools/src/main/scala/org/apache/predictionio/tools/console/Template.scala Some of the URLs in this file are broken and have no replacement.
- bin/install.sh This file should be fixed in [PIO-10](https://issues.apache.org/jira/browse/PIO-10).
> [PIO-5] Replace all *.prediction.io urls

- bin/install.sh
the `-O` option on my system has downloaded the file to `develop` instead of the *.tar.gz file that is used later in the script
> specify the output file explicitely when installing via install.sh script

- README.md
[#docker-installation-for-predictionio](http://predictionio.apache.org/community/projects/#docker-installation-for-predictionio) change to [#docker-images](http://predictionio.apache.org/community/projects/#docker-images) in README.md
> [PIO-180] Trivial LiveDoc link change in readme

- docs/manual/source/resources/upgrade.html.md
In this section:
https://github.com/apache/predictionio/blob/livedoc/docs/manual/source/resources/upgrade.html.md#2-in-xxxalgorithmscala
Line 136:
locate where `LEventStore.findByEntity()` is used, change it to `LEventStore.findByEntity()`
Should be changed to:
locate where `lEventsDb.findSingleEntity()` is used, change it to `LEventStore.findByEntity()`
> [PIO-184] livedoc 0.9.2 upgrade typo

- docs/manual/source/community/contribute-documentation.html.md
Community Contribute Documentation
http://predictionio.apache.org/community/contribute-documentation/
at line 199:
Change `https://git-wip-us.apache.org/repos/asf/predictionio.git`
to `https://gitbox.apache.org/repos/asf/predictionio.git`
> [PIO-185] livedoc Gitbox Link Update

- build.sbt
- doap.rdf
For files, build.sbt & doap.rdf:
Update link from `https://git-wip-us.apache.org/repos/asf/predictionio.git`
to `https://gitbox.apache.org/repos/asf/predictionio.git`
> [PIO-185] develop Gitbox link Update

- data/src/main/scala/org/apache/predictionio/data/store/LEventStore.scala
- data/src/main/scala/org/apache/predictionio/data/store/java/LJavaEventStore.scala
This pull request contains following updates:
- Add async (non-blocking) methods to `LEventStore` and `LJavaEventStore`
- Add Scaladoc about `scala.concurrent.ExecutionContext.Implicits.global` which is used in blocking methods
See also: https://lists.apache.org/thread.html/f14e4f8f29410e4585b3d8e9f646b88293a605f4716d3c4d60771854@%3Cuser.predictionio.apache.org%3E
> [PIO-182] Add async methods to LEventStore

- docs/manual/source/index.html.md.erb
On https://predictionio.apache.org/
`Community Contributed DEMO` and `Community Contributed SDK` are not updated.
> [PIO-191] Web Front-page Community Link Update

- storage/s3/src/main/scala/org/apache/predictionio/data/storage/s3/StorageClient.scala
DefaultAWSCredentialsProviderChain also allows e.g. for AWS Instance Profile Roles and thus is more flexible and does not force developers to include credentials on their PredictionIO machines
> PIO-194: switch to DefaultAWSCredentialsProviderChain which also includes ProfileCredentialsProvider

- build.sbt
Unable to download the artifact from Maven staging repo.
build.sbt
```
name := "template-scala-parallel-classification"
resolvers += "Apache Repository" at
"https://repository.apache.org/content/repositories/orgapachepredictionio-1026"
organization := "org.apache.predictionio"
scalaVersion := "2.11.12"
libraryDependencies ++= Seq(
"org.apache.predictionio" %% "apache-predictionio-core" % "0.14.0" % "provided",
"org.apache.spark"        %% "spark-mllib"              % "2.4.0" % "provided")
```
pio build --verbose
```
[INFO] [Engine$] [warn] ==== Apache Repository: tried
[INFO] [Engine$] [warn]   https://repository.apache.org/content/repositories/orgapachepredictionio-1026/org/apache/predictionio/apache-predictionio-parent_2.11/0.14.0/apache-predictionio-parent_2.11-0.14.0.pom
[INFO] …
```
> Fixes a bug that the parent project is missing from Maven repo

- examples/redeploy-script/redeploy.sh
All,
I have discovered a potential improvement for redeploy-script (predictionio/examples/redeploy-script/redeploy.sh). Details are outlined below.
- Version of PredictionIO - apache-predictionio-0.13.0
- Other components used
- hadoop-2.8.2
- spark-2.1.2
- elasticsearch-5.6.4
- hbase-1.3.2
- openjdk-8-jdk
The redeploy script provided in examples is crucial for production deployments to fully leverage real-time ingestion of events.
However, after extended usage I noticed that whilst `pio deploy` within script successfully undeploys any existing engine instance and binds a new one to the same port; it fails to clear up resources allocated to previous deployment (read as PID continues to linger). Continued usage will lead to lack of memory forcing us to kill stale processes manually.
```zsh …
```
> [PIO-200] Improve redeploy script example
